name: Pandoc Action
# https://github.com/pandoc/pandoc-action-example
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: npm install mermaid-filter
      - name: Node List files 
        id: files_list
        run: |
          ls node_modules/mermaid-filter/ -lha
          pwd
          
          # echo "Lorem ipsum" > lorem_1.md  # create two example files
          # echo "dolor sit amet" > lorem_2.md
          # mkdir output  # create output dir
          # this will also include README.md
          # echo "::set-output name=files::$(printf '"%s" ' *.md)"
          
      - uses: docker://pandoc/latex:2.18
        with:
         # args: --output=output/result.pdf ${{ steps.files_list.outputs.files }}
          args: >- 
            ./README.md
            --citeproc -F pandoc-crossref --mathjax 
            --highlight-style=./my.theme
            --template=./plantilla --pdf-engine-opt=-shell-escape
            -s --toc --toc-depth=2 --number-sections --columns=80
            --output=./README.pdf
            
      - uses: actions/checkout@v2
      - run: mkdir -p src
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./README.pdf
