name: Pandoc Action
# https://github.com/pandoc/pandoc-action-example
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: npm install --location=global mermaid-filter
      - name: file list 
        id: files_list
        run: |
          ls -lha
          pwd
          # echo "Lorem ipsum" > lorem_1.md  # create two example files
          # echo "dolor sit amet" > lorem_2.md
          # mkdir output  # create output dir
          # this will also include README.md
          # echo "::set-output name=files::$(printf '"%s" ' *.md)"
      - uses: docker://pandoc/latex:2.18
        with:
         # args: --output=output/result.pdf ${{ steps.files_list.outputs.files }}
          args: >-  # allows you to break string into multiple lines
            -F pandoc-crossref -C --mathjax 
            --highlight-style=./my.theme
            --template=./plantilla --pdf-engine-opt=-shell-escape
            -s --toc --toc-depth=2 --number-sections --columns=80
            --output README.pdf
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
