name: Pandoc Action
# https://github.com/pandoc/pandoc-action-example
on: push

jobs:
  convert_via_pandoc:
    runs-on:  ubuntu-20.04
    steps:      
      - uses: actions/checkout@v3

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      # - run: sudo ln -s /usr/bin/nodejs /usr/bin/node
      # - run: npm install mermaid-filter

      - name: Set up Python 3
        #uses: actions/setup-python@v2
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # - uses: s-weigand/setup-conda@v1
      #   with:
      #     activate-conda: false
      # - run: conda --version
      # - run: which python

      # - name: Install dependencies
      #   run: |
      #     pyton -V
      #     # $CONDA is an environment variable pointing to the root of the miniconda directory
      #     $CONDA/bin/conda env update --file environment.yml --name base

      #- name: Lint with flake8
      #  run: |
      #    $CONDA/bin/conda install flake8
      #    # stop the build if there are Python syntax errors or undefined names
      #    $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #    $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # - name: Test with pytest
      #   run: |
      #    conda install pytest
      #    $CONDA/bin/pytest

      - name: Install miniconda 
        run: |
          echo $CONDA
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          chmod +x Miniconda3-latest-Linux-x86_64.sh
          ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          #pip install conda
          #conda update conda

      #- name: Install pandoc-plot
      #  run: |
      #    conda install -c conda-forge pandoc-plot
      #     #/usr/share/miniconda/bin/pandoc-plot -h
          
      - run: mkdir -p output

      #- name: List files 
      #  id: files_list
      #  run: |
      #    # ls node_modules -lha
      #    # sudo ls /usr/bin/
      #    ls -lha
      #    ls ./
      #    pwd

      - uses: docker://pandoc/latex:2.18
        with:
          # Problems with c
          # -F node_modules/mermaid-filter/index.js 
          # Error running filter node_modules/mermaid-filter/index.js:
          # env: can't execute 'node': No such file or directory
          
          # -F $CONDA/bin/pandoc-plot 
          # -F /usr/share/miniconda/bin/pandoc-plot 
          # Error running filter $CONDA/bin/pandoc-plot:
          # Could not find executable $CONDA/bin/pandoc-plot
          
          args: 
            #make lite
	    ./README.md -f markdown 
	    --metadata-file=./metadata.yaml --mathjax 
	    -F pandoc-crossref --citeproc 
	    --highlight-style ./vendor/pygments.theme 
	    --template=plantilla --pdf-engine-opt=-shell-escape 
	    -s --toc --toc-depth=2 --number-sections --columns=80 
	    -o ./README.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output/README.pdf
